### ISSUE TITLE
Compatibility with latest versions of Cassandra 

### ISSUE THREAD

**Issue by corporatepiyush** [isoos/cassandart#14]
Is it compatible with Cassandra 4.1 ?

Are there any features this client is missing compared to official client for Java or Go etc.

**Comment by isoos** [comment]
@corporatepiyush: unfortunately I have no idea. I have developed and used the library for a brief period, but I have switched architecture to a different backend, and the development of the library was stalled. If you are interested, I still take PRs, but I don't actively develop or test. (Or feel free to fork if needed).
